### PR TITLE
Normalized (beautified) help messages on node parameters.

### PR DESCRIPTION
**Pull request by adminradio**
Remove (XML) preformatting of help messages for node parameters (preserving paragraphs).

### CODE REVIEW

**Comment by prman-pixar** [comment]
Do you have an example Args file where this change helps? Also, for the first two calls to re.sub, why not combine the two and look for `\s`?

Ian

**Comment by adminradio** [comment]
### Where it helps:
Take a look in "PxrBump.args", the first screenshot below is taken from that file.
RenderMan for Blender reads in the whole xml node <help> without removing the preformatting.
args_xml_node

### What I want to do is from this:
args_help_unfixed
### To this:
args_help_fixed
This creates a natural flow of paragraphs (resolution and font size independent!)

#### Note: UI scaling is 150% (Q4K Monitor, HighDPI)

### RegEx
Combining both re.sub() calls into single search for `\s` will effectively delete also empty lines containing a single `\n`, but they are later needed to distunguish between a single `\n` used as softbreaks **in** a paragraph and double LFs as end of paragraph.

**Comment by prman-pixar** [comment]
OK, thanks for the detailed explanation!

Ian

**Comment by bsavery** [comment]
Just throwing this out there.  Does this look the same on Linux and Windows?  I.e. is that a line ending problem

**Comment by adminradio** [comment]
No, this is a too much whitespace and too much preformatting problem - leeding spaces (see the indention on second screenshot before) and linebreaks in sentences.

Screenshot are taken on Windows, but should be the same on Linux. Its's just a normalization of text flow by removing preformatting and leaving the flow to the presentation (or view) controller (any tree based data model representing text requires such a normalization, it's common practice - see HTML).

**Pull request merged**
