### PR TITLE
Transition to Blender 2.81 [WIP]

### PR DESCRIPTION
**Pull request by Uedaki**

### CODE REVIEW

**Comment by mj-saunders** [comment]
have Pixar finally released updated docs/API for recent releases of RM ProServer?
Or does this remain a totally separate issue?

**Comment by bsavery** [comment]
There is an updated SDK for PRMan 23.  I think @ihsieh

**Comment by Uedaki** [comment]
There is still a lot of warning of type "Class X contains a property which should be an annotation" and few other warning I was planning to fix after.
Should I continue to fix them or should I wait for this project to be updated for PRMan 23?

**Comment by adminradio** [comment]
> There is an updated SDK for PRMan 23.

@bsavery - do you know how to apply to this SDK, or where I can get access to the docs? I'm a bit curious how we can bring the whole plugin to Blender 2.8 and what can I contribute.

**Comment by Uedaki** [comment]
@adminradio , you probably can find some information on this website:
https://rmanwiki.pixar.com/display/REN23/RenderMan

Didnt find any python information in it but I didnt go very deep
I will take a more detailed look tonight

**Comment by mj-saunders** [comment]
is this kind of info useful? https://rmanwiki.pixar.com/display/REN23/Migrating+from+22.x+to+23

API seems to be public, but only SDK I can find is for RM20...

**Comment by Uedaki** [comment]
To be honest, I think making the transition to blender 2.81 should be a priority. Renderman 23 doesnt seem to bring massive change regarding the API.
Right now, loading is free of error but not warning and the plugins crash when you select Renderman as main renderer

**Comment by mj-saunders** [comment]
@Uedaki agreed. fair point.
Good luck and thanks; wish I had the time to be more helpful

**Comment by bsavery** [comment]
I can't speak for them but as the maintainers I'd talk to @prman-pixar, you might want to raise this in a support thread.  The API for 23 is different (at least if used in the "new" way) and they may have other plans here.  

Good luck.

**Comment by Uedaki** [comment]
if there is a new and better way to use the api, it may be better to operate the big changes at the same time to have a cleaner architecture. It will be harder but better for long term I think.

**Comment by Uedaki** [comment]
@bsavery, by support thread you mean issue or something else?

**Comment by Uedaki** [comment]
hey @bsavery, I have some free time and I would like to jump back on renderman for blender. Do you have some documentations on the new way of using Renderman?

**Comment by bsavery** [comment]
I don't officially work on this project anymore.  Ihsieh on the renderman forum or https://renderman.pixar.com/answers/index.html would be your guy.

**Comment by LoganxDev** [comment]
Hello @Uedaki do you think I could help out with the update?

**Comment by Uedaki** [comment]
@bsavery Thank you for your help

**Comment by Uedaki** [comment]
@LoganxDev yes of course
Do you have any experience with Blender api and/or Renderman api?

**Comment by LoganxDev** [comment]
@Uedaki Unfortunately this would be my first time working with both but I've started reading the Blender docs and the code base to get an overall idea of how things are working. I'll pull down your branch tonight to load into blender, it looks like it's still crashing the plugins when Renderman is chosen to render, I can start looking into that. Have you worked with the Blender/Renderman apis previously?

**Comment by Uedaki** [comment]
No, it is a new journey for me too.

yes there is a lot of crash hidden inside. I am focusing on materials right now, there are errors on a lot of shader nodes.

I am going to post a thread on the renderman forum to have some info of the new way of using the renderman api we were discussing earlier

**Comment by LoganxDev** [comment]
Sounds good!
Are you using Renderman 21.5? I have an old download of 22 but I believe you can only get the latest now which is 23.1. I saw above that you were only looking to update the plugin to interface with the new version Blender, I'm just worried the plugin won't work with version 22.

**Comment by Uedaki** [comment]
I am using 23.1

**Comment by Uedaki** [comment]
Ok so I got some news, I ask about this new way of using Renderman and I got this answer:
> This relies on the new scenegraph but it is not yet public.

So we can only fix bugs and train ourselves with blender api before it goes public

**Comment by LoganxDev** [comment]
Gotcha I got it past the first crash I found, but got stuck on this error:

 import prman_for_python_35 as prman_for_python                                                                      ImportError: DLL load failed: The specified module could not be found. 

Might be a problem with my python path though so I'm looking into that. I'm also on python3.7 and unsure if it is supported because there is only prman_for_python_34, prman_for_python_35, and prman_for_python for python 2.

**Comment by Uedaki** [comment]
Could you push and comment the step to reproduce the bug so I can try on my pc?

**Comment by bsavery** [comment]
> Gotcha I got it past the first crash I found, but got stuck on this error:
> 
> import prman_for_python_35 as prman_for_python ImportError: DLL load failed: The specified module could not be found.
> 
> Might be a problem with my python path though so I'm looking into that. I'm also on python3.7 and unsure if it is supported because there is only prman_for_python_34, prman_for_python_35, and prman_for_python for python 2.

The error here should be pretty obvious.  If the version of PRMan you have here only has python bindings for python 3.4 and 3.5, this won't work with blender 2.81 which uses python 3.7.

**Comment by Uedaki** [comment]
So we are blocked until renderman give us a binding for python 3.7?

**Comment by bsavery** [comment]
Perhaps.  Again, I think you need to contact @prman-pixar via support channels.  I would assume they are providing something for Python 3.7 soon due to https://vfxplatform.com/ requirements.

**Comment by bsavery** [comment]
Sorry, I wish I could help more, but no longer work there.

**Comment by Uedaki** [comment]
Yes, I will to do it tonight, maybe they can give me some info. Dont worry, you already help us a lot

It is unrelated to renderman, but does Pixar hire foreigner and what can of project would be a good training/project for a portfolio to do?

**Comment by mistrrhappy** [comment]
https://www.pixar.com/careers-at-pixar

Follow the link above, there is a FAQ regarding hiring.

Good luck!

**Comment by DrachenSeele** [comment]
Good day, may I ask if developement is still continued?
You mentioned that you have to wait untill Pixar releases the API to the public. Have they done so already?
I'm sorry if this comes over as pushy or rude, I'm just curius

**Comment by Uedaki** [comment]
Hi, we cant do anything for now.
Renderman only support binding for python 3.4 and 3.5 which is not compatible with python 3.7 require for blender 2.8x.
I dont follow closely Renderman development but I dont think there is any new release recently

**Comment by DrachenSeele** [comment]
Ah ok, so it is impossible for now? and upgrading the binding is also not possible I suppose?

**Comment by ganeshbelgur** [comment]
Hi guys,

Pixar will be announcing the release of Renderman 24 soon.
And they have an announcement to make about a new Bridge tool.
Hope it is for Blender!

Link to the webinar: https://app.livestorm.co/pixar-animation-studios/new-bridge-tool?utm_source=Livestorm+company+page

**Comment by ganeshbelgur** [comment]
Also take a look at this https://github.com/ian-hsieh/RenderManForBlender

**Comment by Uedaki** [comment]
@ganeshbelgur sounds promising, maybe this pull request will not stay open forever ^^
Does this plugin works with Blender 2.81 or it only works with version prior to 2.8xx? I should try to clone it and try

**Comment by ganeshbelgur** [comment]
It's official! Pixar has confirmed support for Blender 2.83 with Renderman 24! :)

**Comment by mistrrhappy** [comment]
Can you link to the official notice?

Thanks!

**Comment by Uedaki** [comment]
@ganeshbelgur thank you for putting it here, i may have missed it otherwise ^^
@mistrrhappy there is a seminar tomorrow on blender with renderman
https://app.livestorm.co/pixar-animation-studios/new-bridge-tool?utm_source=Livestorm+company+page

**Comment by Uedaki** [comment]
As Pixar will handle it, I will close this pull request at the end of the week

**Comment by Uedaki** [comment]
@mistrrhappy it has be announced during the "What's new in Renderman conference"
here is the slide where they are announcing it: https://imgur.com/a/0fiHmh4

**Comment by ganeshbelgur** [comment]
Yup, they will be going into the specifics of the Blender support today in another webinar. The link to the webinar has been shared above! :)

**Comment by mistrrhappy** [comment]
Thanks for sharing the link.  This is great news!

**Comment by prman-pixar** [comment]
Closing as we will have Blender 2.83 LTS and 2.92 support when RenderMan 24.0 ships.

**Pull request closed without merging**
